
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# highlight
highlight_theme: default

# fireworks
fireworks: false 

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/utils.js
- /js/third-party/anime.min.js
- /js/third-party/jquery.min.js
- /js/third-party/jquery.fancybox.min.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/go-up.js

cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:


